### ISSUE TITLE
could we add the consumer group lag seconds metrics

### ISSUE THREAD

**Issue by yinkp666** [redpanda-data/kminion#251] opened 2024-03-04 03:02 UTC
We find the consumer lag second metrics is more useful for alert,  It is provided by kafka-lag-exporter now.
https://github.com/seglo/kafka-lag-exporter

**Comment by weeco** [comment] 2024-03-04 11:39
Duplicate of https://github.com/redpanda-data/kminion/issues/182

It's a very complicated topic and also has a lot of trade-offs to be considered.

**Closed by weeco** 2024-03-04 11:39 UTC
